-- Users Data
INSERT INTO users (id, password, name, last_name,  birth_date, email, type) VALUES ("0000000", "admin123", "Admin", "Admin", "1990-01-01", "Admin@gmail.com", "admin");
INSERT INTO users (id, password, name, last_name,  birth_date, email, type) VALUES ("5928025", "secret123", "Richard", "Severich", "1994-05-26", "Richard.Severich@gmail.com", "admin");
INSERT INTO users (id, password, name, last_name,  birth_date, email, type) VALUES ("2365874", "pass123", "Cory", "Luza", "1994-10-28", "Cory.Luza@gmail.com", "admin");
INSERT INTO users (id, password, name, last_name,  birth_date, email, type) VALUES ("5123659", "secret255", "Michael", "Jackson", "1984-02-15", "Michael.Jackson@gmail.com", "seller");
INSERT INTO users (id, password, name, last_name,  birth_date, email, type) VALUES ("8475651", "secret987", "Charly", "Garcia", "2000-12-13", "Charly.Garcia@gmail.com", "seller");
INSERT INTO users (id, password, name, last_name,  birth_date, email, type) VALUES ("1236548", "secret654", "Rodrigo", "Molina", "1988-11-11", "Rodrigo.Molina@gmail.com", "seller");
INSERT INTO users (id, password, name, last_name,  birth_date, email, type) VALUES ("0000001", "client123", "Client", "Client", "1990-01-01", "Client@gmail.com", "client");
INSERT INTO users (id, password, name, last_name,  birth_date, email, type) VALUES ("8745698", "mela123", "Rick", "Morris", "1997-06-02", "Rick.Morris@gmail.com", "client");
INSERT INTO users (id, password, name, last_name,  birth_date, email, type) VALUES ("5236567", "kass889", "Rick", "Harrys", "1989-08-15", "Rick.Harrys@gmail.com", "client");
INSERT INTO users (id, password, name, last_name,  birth_date, email, type) VALUES ("7896321", "mula777", "Andrea", "Flores", "1997-07-06", "Andrea.Flores@gmail.com", "client");
INSERT INTO users (id, password, name, last_name,  birth_date, email, type) VALUES ("5928354", "cass222", "Liza", "Simpson", "1992-03-18", "Liza.Simpson@gmail.com", "client");
INSERT INTO users (id, password, name, last_name,  birth_date, email, type) VALUES ("2136545", "upa4848", "Iza", "Ortega", "1995-05-27", "Iza.Ortega@gmail.com", "client");
INSERT INTO users (id, password, name, last_name,  birth_date, email, type) VALUES ("7812653", "vela778", "Emily", "Syler", "1996-04-03", "Emily.Syler@gmail.com", "client");
INSERT INTO users (id, password, name, last_name,  birth_date, email, type) VALUES ("9814256", "user555", "Mario", "Bros", "1999-08-08", "Mario.Bros@gmail.com", "client");
INSERT INTO users (id, password, name, last_name,  birth_date, email, type) VALUES ("6636666", "mela888", "Mario", "Bros", "1998-08-08", "Mario.Bros@gmail.com", "client");
INSERT INTO users (id, password, name, last_name,  birth_date, email, type) VALUES ("9825789", "reyleon", "Ariel", "Moppu", "1997-02-12", "Ariel.Moppu@gmail.com", "client");
INSERT INTO users (id, password, name, last_name,  birth_date, email, type) VALUES ("9985501", "pass555", "Manfred", "Reyes", "1985-12-25", "Manfred.Reyes@gmail.com", "client");
INSERT INTO users (id, password, name, last_name,  birth_date, email, type) VALUES ("9985502", "mysecret", "Igor", "Cruz", "1987-08-28", "Igor.Cruz@gmail.com", "client");
INSERT INTO users (id, password, name, last_name,  birth_date, email, type) VALUES ("9985503", "secret", "Daniel", "Vera", "1997-03-11", "Daniel.Vera@gmail.com", "client");
INSERT INTO users (id, password, name, last_name,  birth_date, email, type) VALUES ("9985504", "nasa", "Keyur", "Rpuu", "1997-04-10", "Keyur.Rpuu@gmail.com", "client");

-- Items Data
INSERT INTO items (name, price, stock) VALUES ("1L-Cocacola", 8, 10);
INSERT INTO items (name, price, stock) VALUES ("2L-Cocacola", 12, 8);
INSERT INTO items (name, price, stock) VALUES ("3L-Cocacola", 16, 50);
INSERT INTO items (name, price, stock) VALUES ("CervezaTaqu", 20, 80);
INSERT INTO items (name, price, stock) VALUES ("CervezaHuar", 25, 90);
INSERT INTO items (name, price, stock) VALUES ("CervezaCoro", 15, 55);
INSERT INTO items (name, price, stock) VALUES ("CervezaCont", 5, 100);
INSERT INTO items (name, price, stock) VALUES ("Te Dharamsala", 18, 39);
INSERT INTO items (name, price, stock) VALUES ("Te Dharamsala", 18.50, 39);
INSERT INTO items (name, price, stock) VALUES ("Cerveza tibetana Barley",19, 17);
INSERT INTO items (name, price, stock) VALUES ("Sirope de regaliz",10, 13);
INSERT INTO items (name, price, stock) VALUES ("Especias Cajun del chef Anton",22, 53);
INSERT INTO items (name, price, stock) VALUES ("Mezcla Gumbo del chef Anton", 21, 35);
INSERT INTO items (name, price, stock) VALUES ("Mermelada de grosellas de la abuela", 25, 120);
INSERT INTO items (name, price, stock) VALUES ("Peras secas orgánicas del tío Bob", 30, 15);
INSERT INTO items (name, price, stock) VALUES ("Salsa de arándanos Northwoods", 40, 6);
INSERT INTO items (name, price, stock) VALUES ("Buey Mishi Kobe", 97 ,29);
INSERT INTO items (name, price, stock) VALUES ("Pez espada", 31, 31);
INSERT INTO items (name, price, stock) VALUES ("Queso Cabrales", 21, 22);
INSERT INTO items (name, price, stock) VALUES ("Queso Manchego La Pastora", 38, 86);
INSERT INTO items (name, price, stock) VALUES ("Algas Konbu", 6, 24);
INSERT INTO items (name, price, stock) VALUES ("Cuajada de judías", 23.25, 35);
INSERT INTO items (name, price, stock) VALUES ("Salsa de soja baja en sodio", 15.50, 39);
INSERT INTO items (name, price, stock) VALUES ("Postre de merengue Pavlova", 17.45, 29);
INSERT INTO items (name, price, stock) VALUES ("Cordero Alice Springs", 39, 0);
INSERT INTO items (name, price, stock) VALUES ("Langostinos tigre Carnarvon", 62.50, 42);
INSERT INTO items (name, price, stock) VALUES ("Pastas de té de chocolate", 9.20, 25);
INSERT INTO items (name, price, stock) VALUES ("Mermelada de Sir Rodney's", 81, 40);
INSERT INTO items (name, price, stock) VALUES ("Bollos de Sir Rodney's", 10, 3);
INSERT INTO items (name, price, stock) VALUES ("Pan de centeno crujiente estilo Gustaf's", 21, 104);
INSERT INTO items (name, price, stock) VALUES ("Pan fino", 9, 61);
INSERT INTO items (name, price, stock) VALUES ("Refresco Guaraná Fantástica",4.50, 20);
INSERT INTO items (name, price, stock) VALUES ("Crema de chocolate y nueces NuNuCa", 14, 76);
INSERT INTO items (name, price, stock) VALUES ("Ositos de goma Gumbär", 31.23, 15);
INSERT INTO items (name, price, stock) VALUES ("Chocolate Schoggi", 43.90, 49);
INSERT INTO items (name, price, stock) VALUES ("Col fermentada Rössle", 45.60, 26);
INSERT INTO items (name, price, stock) VALUES ("Salchicha Thüringer", 123.79, 0);
INSERT INTO items (name, price, stock) VALUES ("Arenque blanco del noroeste", 25.89, 10);
INSERT INTO items (name, price, stock) VALUES ("Queso gorgonzola Telino", 12.50, 0);
INSERT INTO items (name, price, stock) VALUES ("Queso Mascarpone Fabioli", 32, 9);
INSERT INTO items (name, price, stock) VALUES ("Queso de cabra", 2.50, 112);
INSERT INTO items (name, price, stock) VALUES ("Cerveza Sasquatch", 14, 111);
INSERT INTO items (name, price, stock) VALUES ("Cerveza negra Steeleye", 18, 20);
INSERT INTO items (name, price, stock) VALUES ("Escabeche de arenque", 19, 112);
INSERT INTO items (name, price, stock) VALUES ("Salmón ahumado Gravad", 26, 11);
INSERT INTO items (name, price, stock) VALUES ("Vino Côte de Blaye", 263.50, 17);
INSERT INTO items (name, price, stock) VALUES ("Licor verde Chartreuse", 18, 69);
INSERT INTO items (name, price, stock) VALUES ("Carne de cangrejo de Boston", 18.40, 123);
INSERT INTO items (name, price, stock) VALUES ("Crema de almejas estilo Nueva Inglaterra", 9.65, 85);
INSERT INTO items (name, price, stock) VALUES ("Tallarines de Singapur", 14, 26);
INSERT INTO items (name, price, stock) VALUES ("Café de Malasia", 46, 17);
INSERT INTO items (name, price, stock) VALUES ("Azúcar negra Malacca", 19.45, 27);
INSERT INTO items (name, price, stock) VALUES ("Arenque ahumado", 9.50, 5);
INSERT INTO items (name, price, stock) VALUES ("Arenque salado", 12, 95);
INSERT INTO items (name, price, stock) VALUES ("Galletas Zaanse", 9.50, 36);
INSERT INTO items (name, price, stock) VALUES ("Chocolate holandés", 12.75, 15);
INSERT INTO items (name, price, stock) VALUES ("Regaliz", 20, 10);
INSERT INTO items (name, price, stock) VALUES ("Chocolate blanco", 16.25, 65);
INSERT INTO items (name, price, stock) VALUES ("Manzanas secas Manjimup", 53, 20);
INSERT INTO items (name, price, stock) VALUES ("Cereales para Filo",7 ,38);
INSERT INTO items (name, price, stock) VALUES ("Empanada de carne", 32.80, 0);
INSERT INTO items (name, price, stock) VALUES ("Empanada de cerdo", 7.45, 21);
INSERT INTO items (name, price, stock) VALUES ("Paté chino", 24, 115);
INSERT INTO items (name, price, stock) VALUES ("Gnocchi de la abuela Alicia", 38, 21);
INSERT INTO items (name, price, stock) VALUES ("Raviolis Angelo", 19.50, 36);
INSERT INTO items (name, price, stock) VALUES ("Caracoles de Borgoña", 13.25, 62);
INSERT INTO items (name, price, stock) VALUES ("Raclet de queso Courdavault", 55, 79);
INSERT INTO items (name, price, stock) VALUES ("Camembert Pierrot", 34, 19);
INSERT INTO items (name, price, stock) VALUES ("Sirope de arce", 28.50, 113);
INSERT INTO items (name, price, stock) VALUES ("Tarta de azúcar", 49.30, 17);
INSERT INTO items (name, price, stock) VALUES ("Sandwich de vegetales", 43.90, 24);
INSERT INTO items (name, price, stock) VALUES ("Bollos de pan de Wimmer", 33.25, 22);
INSERT INTO items (name, price, stock) VALUES ("Salsa de pimiento picante de Luisiana", 21.05, 76);
INSERT INTO items (name, price, stock) VALUES ("Especias picantes de Luisiana", 17, 4);
INSERT INTO items (name, price, stock) VALUES ("Cerveza Laughing Lumberjack", 14, 52);
INSERT INTO items (name, price, stock) VALUES ("Barras de pan de Escocia", 12.50, 6);
INSERT INTO items (name, price, stock) VALUES ("Queso Gudbrandsdals", 36 ,26);
INSERT INTO items (name, price, stock) VALUES ("Cerveza Outback", 15, 15);
INSERT INTO items (name, price, stock) VALUES ("Crema de queso Fløtemys", 21.50, 26);
INSERT INTO items (name, price, stock) VALUES ("Queso Mozzarella Giovanni", 34.80, 14);
INSERT INTO items (name, price, stock) VALUES ("Caviar rojo", 15, 101);
INSERT INTO items (name, price, stock) VALUES ("Queso de soja Longlife", 10, 4);
INSERT INTO items (name, price, stock) VALUES ("Cerveza Klosterbier Rhönbräu",7.75 ,125);
INSERT INTO items (name, price, stock) VALUES ("Licor Cloudberry",18 ,57);
INSERT INTO items (name, price, stock) VALUES ("Salsa verde original Frankfurter",13 ,32);

-- Sales Data
INSERT INTO sales (id_seller, id_client, date) VALUES ("0000000", "0000001", "2019-07-25");
INSERT INTO sales (id_seller, id_client, date) VALUES ("0000000", "9985504", "2019-07-25");

-- Sales - Items Data
INSERT INTO sales_items (id_sale, id_item, quantity) VALUES (1001, 1001, 1);
INSERT INTO sales_items (id_sale, id_item, quantity) VALUES (1001, 1002, 1);
INSERT INTO sales_items (id_sale, id_item, quantity) VALUES (1001, 1003, 1);
